name: release-pypi

on:
  push:
    # Publish `v*` tags as releases.
    tags:
      - v*

jobs:
  release-pypi:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Install from source (required for the pre-commit tests)
        run: pip install .

      - name: Test with pytest
        run: |
          pytest -v

      - name: Publish to pypi
        run: |
          python -m pip install build twine
          python -m build .
          twine upload -r pypi -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} --verbose dist/*
