name: release-pypi

on:
  release:
    types: [created]

on:
  push:
    # Publish `v*` tags as releases.
    tags:
      - v*


jobs:
  publish-pypi:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Install from source (required for the pre-commit tests)
        run: pip install .

      - name: Test with pytest
        run: |
          pytest -v

      - name: publish to pypi
        run: |
          python -m pip install build twine
          python -m build .
          ls dist/*
          twine upload
          --repository-url https://test.pypi.org/legacy/
          -u shashank.gopikrishna
          -p ${{ secrets.TEST_PYPI_API_TOKEN }}
